name: Website of The Joseph Turner
markdown: redcarpet
pygments: true
url: http://thejosephturner.com/
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/post/:title
